{
 "title": "Video Analysis 2.0",
 "time": { "from": "2024-04-18T12:59:23.603Z", "to": "2024-04-18T13:05:53.590Z" },
 "templating": {
  "list": [
   {
    "name": "Video",
    "query": "select DISTINCT camera from object_tracker where \"location\"::tag =~ /^$Locations$/;"
   },
   {
    "name": "Locations",
    "query": "select DISTINCT location from locations;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "options": {
    "content": "<a href=\"https://precrisis.smartcommunitylab.it/\">\n\n<h3>Home</h3>\n</a>\n\n<h1>${Locations}</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Anomaly Detection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "alias": "Anomaly Score",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "video_anomaly_score",
     "select": [
      [
       { "params": [ "score" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "camera::tag", "operator": "=~", "value": "/^$Video$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Pedestrians",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "alias": "Number of Pedestrians",
     "measurement": "object_tracker",
     "select": [
      [
       { "params": [ "number_objects" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "camera::tag", "operator": "=~", "value": "/^$Video$/" }
     ]
    }
   ]
  },
  {
   "title": "Camera Sample (Click to See More Details)",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "measurement": "thumbnails_busca",
     "select": [
      [
       { "params": [ "image" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Crowd Violence Activity Detection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 10 },
   "targets": [
    {
     "alias": "Violence Score",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "crowd_violence",
     "select": [
      [
       { "params": [ "prob" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "camera::tag", "operator": "=~", "value": "/^$Video$/" }
     ]
    }
   ]
  },
  {
   "title": "Persistence of Pedestrians (Frames)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "alias": "Mean",
     "measurement": "object_tracker",
     "select": [
      [
       { "params": [ "avg_age" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "camera::tag", "operator": "=~", "value": "/^$Video$/" }
     ]
    },
    {
     "alias": "Min Pedestrian",
     "measurement": "object_tracker",
     "select": [
      [
       { "params": [ "min_age" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "camera::tag", "operator": "=~", "value": "/^$Video$/" }
     ]
    },
    {
     "alias": "Min Pedestrian",
     "measurement": "object_tracker",
     "select": [
      [
       { "params": [ "high_age" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "camera::tag", "operator": "=~", "value": "/^$Video$/" }
     ]
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "clips",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "clips",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Points of Interest",
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "builds",
     "measurement": "points_of_interest",
     "query": "SELECT \"geojson\" FROM \"points_of_interest\" WHERE (\"location\"::tag =~ /^$Locations$/ AND \"radius\"::tag = '500' AND \"poi_type\"::tag = 'buildings')",
     "select": [
      [
       { "params": [ "geojson" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=~", "value": "/^$Locations$/" },
      { "condition": "AND", "key": "radius::tag", "operator": "=", "value": "500" },
      { "condition": "AND", "key": "poi_type::tag", "operator": "=", "value": "buildings" }
     ]
    },
    {
     "alias": "poi",
     "measurement": "points_of_interest",
     "query": "SELECT \"geojson\" FROM \"points_of_interest\" WHERE (\"location\"::tag =~ /^$Locations$/ AND \"radius\"::tag = '500' AND \"poi_type\"::tag = 'pois_gdf')",
     "select": [
      [
       { "params": [ "geojson" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=~", "value": "/^$Locations$/" },
      { "condition": "AND", "key": "radius::tag", "operator": "=", "value": "500" },
      { "condition": "AND", "key": "poi_type::tag", "operator": "=", "value": "buildings" }
     ]
    }
   ]
  },
  {
   "title": "Crowd Panic Activity Detection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 20 },
   "targets": [
    {
     "alias": "Violence Score",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "panic_module",
     "select": [
      [
       { "params": [ "score" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "camera::tag", "operator": "=~", "value": "/^$Video$/" }
     ]
    }
   ]
  },
  {
   "title": "Pedestrian Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "alias": "Object Speed",
     "measurement": "object_tracker",
     "select": [
      [
       { "params": [ "avg_speed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "camera::tag", "operator": "=~", "value": "/^$Video$/" }
     ]
    },
    {
     "alias": "Object Speed",
     "measurement": "object_tracker",
     "select": [
      [
       { "params": [ "highest_speed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "camera::tag", "operator": "=~", "value": "/^$Video$/" }
     ]
    }
   ]
  }
 ]
}